; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 2
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Tetris
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4 ; 01 : Tetris DPCM
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env4,@env5,@env0 ; 00 : Bass
	.word @env1,@env4,@env5,@env0 ; 01 : Drum
	.word @env2,@env4,@env6,@env0 ; 02 : Lead

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$ca,$c5,$c0,$00,$04
@env2:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$00,$08
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $c2,$7f,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0c,$0f,$40 ; 00 BassDrum (Pitch:15)
	.byte $03+.lobyte(FAMISTUDIO_DPCM_PTR),$30,$0f,$40 ; 01 Snare (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $84, $29, $b5, $24, $99, $25, $99, $27, $b5, $25, $99, $24
	.byte $99, $47, $22, $b5, $22, $99, $25, $99, $29, $b5, $27, $99, $25, $99, $47, $24, $b5, $24, $99, $25, $99, $27, $b5, $29
	.byte $b5, $47, $25, $b5, $22, $b5, $22, $b5, $00, $b5, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $78, $b7, $84, $21, $99, $00, $d1, $22, $99, $21, $99, $1d, $b5, $00, $ff, $a5, $21, $b5, $21, $99, $22, $99, $24, $b5
	.byte $00, $b5, $ff, $df, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $1d, $99, $29, $99, $1d, $99, $29, $99, $1d, $99, $29, $99, $1d, $99, $29
@song0ref103:
	.byte $99, $16, $99, $22, $99, $16, $99, $22, $99, $16, $99, $22, $99, $16, $99, $22, $99, $15, $99, $21, $99, $15, $99, $21
	.byte $99, $15, $99, $21, $99, $15, $99, $21
	.byte $41, $11
	.word @song0ref103
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $00, $99, $82
@song0ref145:
	.byte $31, $99, $00, $99, $31, $99, $00, $99, $31, $8b, $31, $8b, $00, $99, $31, $99, $00, $99
	.byte $41, $12
	.word @song0ref145
	.byte $41, $12
	.word @song0ref145
	.byte $41, $10
	.word @song0ref145
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $df, $ff, $df, $ff, $df, $ff, $df, $42
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $84, $29, $b5, $24, $99, $25, $99, $27, $b5, $25, $99, $24
	.byte $99, $47, $22, $b5, $22, $99, $25, $99, $29, $b5, $27, $99, $25, $99, $47, $24, $b5, $24, $99, $25, $99, $27, $b5, $29
	.byte $b5, $47, $25, $b5, $22, $b5, $22, $b5, $00, $b5, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $78, $b7, $84, $21, $99, $00, $d1, $22, $99, $21, $99, $1d, $b5, $00, $ff, $a5, $21, $b5, $21, $99, $22, $99, $24, $b5
	.byte $00, $b5, $ff, $df, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $80, $1d, $99, $29, $99, $1d, $99, $29, $99, $1d, $99, $29, $99, $1d, $99, $29
@song1ref103:
	.byte $99, $16, $99, $22, $99, $16, $99, $22, $99, $16, $99, $22, $99, $16, $99, $22, $99, $15, $99, $21, $99, $15, $99, $21
	.byte $99, $15, $99, $21, $99, $15, $99, $21
	.byte $41, $11
	.word @song1ref103
	.byte $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $ff, $df, $ff, $df, $ff, $df, $ff, $df, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref154:
	.byte $01, $99, $02, $99, $01, $99, $02, $99, $01, $99, $02, $8b, $02, $8b, $01, $99, $02, $99
	.byte $41, $12
	.word @song1ref154
	.byte $41, $12
	.word @song1ref154
	.byte $41, $12
	.word @song1ref154
	.byte $42
	.word @song1ch4loop
